/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.experimental.noauth;

import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.common.ConsoleNotifier;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.post;
import static com.github.tomakehurst.wiremock.core.WireMockConfiguration.options;

public class Demo {

    public static void main(String[] args) {
        WireMockServer wireMockServer = new WireMockServer(options()
                .extensions(new TokenTransformer()).port(7777)
                .notifier(new ConsoleNotifier(true))
        );

        wireMockServer.stubFor(
                post("/token-info").willReturn(aResponse().withTransformers("token-transformer"))
        );

        wireMockServer.start();
    }
}
